### ISSUE TITLE
Packaging for Debian

### ISSUE THREAD

**Issue by geor-g** [jwilk/mwic#6]
Hi Jakub,

Thanks for your work on this. I'm interested in packaging this in Debian, and there is also a [RFP](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849327): Anything which speaks against it or I should be aware of?

Cheers,
Georg

**Comment by jwilk** [comment]
Please go ahead. :+1:

You may want to copy some packaging bits from [src:i18nspector](https://salsa.debian.org/debian/i18nspector), which is similarly structured.

Please consider using http://jwilk.net/software/mwic in the Homepage field (not https://github.com/jwilk/mwic as RFP says).

**Comment by geor-g** [comment]
Thanks for the pointer to i18nspector, and I'll use the correct homepage as well. Could you add me to the debian group on salsa, AFAIK, this replaces collab-maint on alioth.d.o, correct? I'm georg-guest over there.

**Comment by jwilk** [comment]
As I understand it, the only way to be added to the `debian` group is to become a DD. [Salsa documentation](https://wiki.debian.org/Salsa/Doc#Projects_and_Repositories) reads:
> non-DDs (DMs or external contributors) need to be explicitly granted commit privileges for single projects

My recommendation is to use a hosting service that doesn't require you to jump through such bureaucratic hops, e.g. GitHub.
If you insist on using Salsa, please ask on debian-mentors. I'm boycotting Salsa because of its heavy reliance on JavaScript.

**Comment by geor-g** [comment]
Are you interested in reviewing / sponsoring this, or should I rather find someone else?

**Comment by jwilk** [comment]
Please find somebody else. Sorry!

**Comment by geor-g** [comment]
Jakub, no need to say sorry! Thanks for your work! It's now pending review of the Debian Python team, and I hope it'll hit NEW soon. Cheers!

**Comment by geor-g** [comment]
Just for the record: This entered NEW now. Will update (and close) once again the package enters the archive.

**Comment by geor-g** [comment]
ACCEPTED into unstable, just now. Closing then, thanks! :)
